import { defineStore } from 'pinia'

export const Gen9 = defineStore('main', {
  state: () => {
    return ({
      pokemons: [
        'Charmander', 'Charmeleon', 'Charizard', 'Pikachu', 'Raichu', 'Jigglypuff', 'Wigglytuff', 'Venonat', 'Venomoth', 'Diglett',
        'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Slowpoke',
        'Slowbro', 'Magnemite', 'Magneton', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
        'Gengar', 'Drowzee', 'Hypno', 'Voltorb', 'Electrode', 'Chansey', 'Scyther', 'Tauros', 'Magikarp', 'Gyarados',
        'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
        'Dragonite', 'Mewtwo', 'Mew', 'Cyndaquil', 'Quilava', 'Typhlosion', 'Pichu', 'Igglybuff', 'Mareep', 'Flaaffy',
        'Ampharos', 'Marill', 'Azumarill', 'Sudowoodo', 'Hoppip', 'Skiploom', 'Jumpluff', 'Sunkern', 'Sunflora', 'Wooper',
        'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking', 'Misdreavus', 'Girafarig', 'Pineco', 'Forretress', 'Dunsparce',
        'Qwilfish', 'Scizor', 'Heracross', 'Sneasel', 'Teddiursa', 'Ursaring', 'Delibird', 'Houndour', 'Houndoom', 'Phanpy',
        'Donphan', 'Stantler', 'Blissey', 'Larvitar', 'Pupitar', 'Tyranitar', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia',
        'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Makuhita', 'Hariyama',
        'Azurill', 'Sableye', 'Meditite', 'Medicham', 'Gulpin', 'Swalot', 'Numel', 'Camerupt', 'Torkoal', 'Spoink',
        'Grumpig', 'Cacnea', 'Cacturne', 'Swablu', 'Altaria', 'Zangoose', 'Seviper', 'Barboach', 'Whiscash', 'Shuppet',
        'Banette', 'Tropius', 'Snorunt', 'Glalie', 'Luvdisc', 'Bagon', 'Shelgon', 'Salamence', 'Kyogre', 'Groudon',
        'Rayquaza', 'Starly', 'Staravia', 'Staraptor', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio', 'Luxray', 'Combee',
        'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel', 'Shellos', 'Gastrodon', 'Drifloon', 'Drifblim', 'Mismagius', 'Honchkrow',
        'Stunky', 'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly', 'Happiny', 'Spiritomb', 'Gible', 'Gabite', 'Garchomp',
        'Riolu', 'Lucario', 'Hippopotas', 'Hippowdon', 'Croagunk', 'Toxicroak', 'Finneon', 'Lumineon', 'Snover', 'Abomasnow',
        'Weavile', 'Magnezone', 'Leafeon', 'Glaceon', 'Gallade', 'Froslass', 'Rotom', 'Uxie', 'Mesprit', 'Azelf',
        'Dialga', 'Palkia', 'Heatran', 'Giratina', 'Cresselia', 'Arceus', 'Oshawott', 'Dewott', 'Samurott', 'Petilil',
        'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile', 'Zorua', 'Zoroark', 'Gothita', 'Gothorita', 'Gothitelle',
        'Deerling', 'Sawsbuck', 'Foongus', 'Amoonguss', 'Alomomola', 'Tynamo', 'Eelektrik', 'Eelektross', 'Axew', 'Fraxure',
        'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Pawniard', 'Bisharp', 'Rufflet', 'Braviary', 'Deino', 'Zweilous',
        'Hydreigon', 'Larvesta', 'Volcarona', 'Tornadus', 'Thundurus', 'Landorus', 'Meloetta', 'Chespin', 'Quilladin', 'Chesnaught',
        'Fennekin', 'Braixen', 'Delphox', 'Froakie', 'Frogadier', 'Greninja', 'Fletchling', 'Fletchinder', 'Talonflame', 'Scatterbug',
        'Spewpa', 'Vivillon', 'Litleo', 'Pyroar', 'Flabebe', 'Floette', 'Florges', 'Skiddo', 'Gogoat', 'Skrelp',
        'Dragalge', 'Clauncher', 'Clawitzer', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy', 'Sliggoo', 'Goodra',
        'Klefki', 'Bergmite', 'Avalugg', 'Noibat', 'Noivern', 'Diancie', 'Hoopa', 'Volcanion', 'Rowlet', 'Dartrix',
        'Decidueye', 'Yungoos', 'Gumshoos', 'Crabrawler', 'Crabominable', 'Oricorio-Baile', 'Rockruff', 'Lycanroc-Midday', 'Mareanie', 'Toxapex',
        'Mudbray', 'Mudsdale', 'Fomantis', 'Lurantis', 'Salandit', 'Salazzle', 'Bounsweet', 'Steenee', 'Tsareena', 'Oranguru',
        'Passimian', 'Sandygast', 'Palossand', 'Komala', 'Mimikyu', 'Bruxish', 'Magearna', 'Grookey', 'Thwackey', 'Rillaboom',
        'Scorbunny', 'Raboot', 'Cinderace', 'Sobble', 'Drizzile', 'Inteleon', 'Skwovet', 'Greedent', 'Rookidee', 'Corvisquire',
        'Corviknight', 'Chewtle', 'Drednaw', 'Rolycoly', 'Carkol', 'Coalossal', 'Applin', 'Flapple', 'Appletun', 'Silicobra',
        'Sandaconda', 'Arrokuda', 'Barraskewda', 'Toxel', 'Toxtricity', 'Sinistea', 'Polteageist', 'Hatenna', 'Hattrem', 'Hatterene',
        'Impidimp', 'Morgrem', 'Grimmsnarl', 'Perrserker', 'Falinks', 'Pincurchin', 'Snom', 'Frosmoth', 'Stonjourner', 'Eiscue',
        'Indeedee-M', 'Cufant', 'Copperajah', 'Dreepy', 'Drakloak', 'Dragapult', 'Zacian', 'Zamazenta', 'Eternatus', 'Kubfu',
        'Urshifu-Single Strike', 'Zarude', 'Regieleki', 'Regidrago', 'Glastrier', 'Spectrier', 'Calyrex', 'Wyrdeer', 'Kleavor', 'Ursaluna',
        'Basculegion', 'Sneasler', 'Overqwil', 'Enamorus', 'Sprigatito', 'Floragato', 'Meowscarada', 'Fuecoco', 'Crocalor', 'Skeledirge',
        'Quaxly', 'Quaxwell', 'Quaquaval', 'Lechonk', 'Oinkologne', 'Dudunsparce', 'Tarountula', 'Spidops', 'Nymble', 'Lokix',
        'Rellor', 'Rabsca', 'Greavard', 'Houndstone', 'Flittle', 'Espathra', 'Farigiraf', 'Wiglett', 'Wugtrio', 'Dondozo',
        'Veluza', 'Finizen', 'Palafin', 'Smoliv', 'Dolliv', 'Arboliva', 'Capsakid', 'Scovillain', 'Tadbulb', 'Bellibolt',
        'Varoom', 'Revavroom', 'Orthworm', 'Tandemaus', 'Maushold', 'Cetoddle', 'Cetitan', 'Frigibax', 'Arctibax', 'Baxcalibur',
        'Tatsugiri', 'Cyclizar', 'Pawmi', 'Pawmo', 'Pawmot', 'Wattrel', 'Kilowattrel', 'Bombirdier', 'Squawkabilly', 'Flamigo',
        'Klawf', 'Nacli', 'Naclstack', 'Garganacl', 'Glimmet', 'Glimmora', 'Shroodle', 'Grafaiai', 'Fidough', 'Dachsbun',
        'Maschiff', 'Mabosstiff', 'Bramblin', 'Brambleghast', 'Gimmighoul', 'Gholdengo', 'Ting-Lu', 'Chien-Pao', 'Wo-Chien', 'Chi-Yu',
        'Tinkatink', 'Tinkatuff', 'Tinkaton', 'Charcadet', 'Armarouge', 'Ceruledge', 'Toedscool', 'Toedscruel', 'Kingambit', 'Clodsire',
        'Annihilape', 'Great Tusk', 'Brute Bonnet', 'Sandy Shocks', 'Scream Tail', 'Flutter Mane', 'Slither Wing', 'Roaring Moon', 'Iron Treads', 'Iron Moth',
        'Iron Hands', 'Iron Jugulis', 'Iron Thorns', 'Iron Bundle', 'Iron Valiant', 'Koraidon', 'Miraidon', 'Raichu-Alola', 'Diglett-Alola', 'Dugtrio-Alola', 'Meowth-Alola', 'Meowth-Galar', 'Persian-Alola', 'Growlithe-Hisui', 'Arcanine-Hisui', 'Slowpoke-Galar', 'Slowbro-Galar',
        'Grimer-Alola', 'Muk-Alola', 'Voltorb-Hisui', 'Electrode-Hisui', 'Tauros-Paldea', 'Tauros-Paldea-Fire', 'Tauros-Paldea-Water', 'Articuno-Galar', 'Zapdos-Galar', 'Moltres-Galar',
        'Typhlosion-Hisui', 'Slowking-Galar', 'Qwilfish-Hisui', 'Sneasel-Hisui', 'Rotom-Heat', 'Rotom-Wash', 'Rotom-Frost', 'Rotom-Fan', 'Rotom-Mow', 'Dialga-Origin',
        'Palkia-Origin', 'Giratina-Origin', 'Samurott-Hisui', 'Lilligant-Hisui', 'Zorua-Hisui', 'Zoroark-Hisui', 'Braviary-Hisui', 'Tornadus-Therian', 'Thundurus-Therian', 'Landorus-Therian',
        'Meloetta-Pirouette', 'Sliggoo-Hisui', 'Goodra-Hisui', 'Avalugg-Hisui', 'Decidueye-Hisui', 'Oricorio-Pom-Pom', "Oricorio-Pa'u", 'Oricorio-Sensu', 'Lycanroc-Midnight', 'Lycanroc-Dusk',
        'Eiscue-Noice', 'Indeedee-F', 'Zacian-Crowned', 'Zamazenta-Crowned', 'Urshifu-Rapid Strike', 'Calyrex-Ice Rider', 'Calyrex-Shadow Rider', 'Basculegion-F', 'Enamorus-Therian', 'Oinkologne-F',
        'Dudunsparce-Big', 'Palafin-Hero', 'Maushold-Four', 'Gimmighoul-Roam', 'Hoopa-Unbound', 'Wooper-Paldea'
      ],
    })
  }
})